sudo: required
services:
  - docker

before_install:
  - docker build -t dennissimoni/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dennissimoni/react-test npm test

after_success:
  - docker build -t dennissimoni/multi-client ./client
  - docker build -t dennissimoni/multi-nginx ./nginx
  - docker build -t dennissimoni/multi-server ./server
  - docker build -t dennissimoni/multi-worker ./worker

# login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push to docker hub 
  - docker push dennissimoni/multi-client 
  - docker push dennissimoni/multi-nginx
  - docker push dennissimoni/multi-server 
  - docker push dennissimoni/multi-worker 